skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2013

environment:
  BOOST_ROOT: C:\Libraries\boost

cache:
  - thirdparty.cached -> appveyor.install.bat
  - thirdparty\bin -> appveyor.install.bat
  - thirdparty\data -> appveyor.install.bat
  - thirdparty\include -> appveyor.install.bat
  - thirdparty\lib -> appveyor.install.bat
  - C:\Libraries\boost -> appveyor.install.bat

init:
  - git --version
  - cmake --version
  - msbuild /version
  - git config --global core.autocrlf true

install:
  - .\appveyor.install.bat

build_script:
  - .\build.bat test

after_build:
  - dir build /s

before_test:
  - copy /y build\lib\Release\rime.dll build\bin
  - copy /y thirdparty\bin\*.dll build\bin

test_script:
  - cd build\bin
  - echo "congmingdeRime{space}shurufa" | Release\rime_api_console
