skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} static build {build}'
image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\libboost

cache:
  - thirdparty.cached -> appveyor.install.bat
  - thirdparty\bin -> appveyor.install.bat
  - thirdparty\data -> appveyor.install.bat
  - thirdparty\include -> appveyor.install.bat
  - thirdparty\lib -> appveyor.install.bat
  - C:\Libraries\libboost -> appveyor.install.bat

init:
  - git --version
  - cmake --version
  - msbuild /version
  - git config --global core.autocrlf true

install:
  - .\appveyor.install.bat

build_script:
  - .\build.bat static

after_build:
  - 7z a rime.zip %CD%\build\bin %CD%\build\lib
  - dir build /s

test_script:
  - cd build\bin
  - echo "congmingdeRime{space}shurufa" | Release\rime_api_console.exe

artifacts:
  - path: rime.zip
    name: Binaries
